//! Shared structures for eBPF <-> Userspace communication
//!
//! This module defines the data structures used for communication between
//! the eBPF kernel programs and the userspace daemon. All structures are
//! designed to match their C counterparts for binary compatibility.

/// Configuration structure shared between userspace and BPF kernel program
///
/// This struct controls the DPI (Deep Packet Inspection) bypass techniques
/// that will be applied to network traffic. It is passed from userspace
/// to the BPF program via a map.
///
/// # Example
/// ```
/// use goodbyedpi_proto::Config;
///
/// let config = Config {
///     split_pos: 10,      // Split HTTP requests at byte 10
///     oob_pos: 5,         // Insert OOB data at byte 5
///     fake_offset: -1,    // Fake packet offset
///     tlsrec_pos: 1,      // TLS record split position
///     auto_rst: true,     // Auto-detect RST packets
///     auto_redirect: false,
///     auto_ssl: false,
///     ip_fragment: 1,     // Enable IP fragmentation for QUIC
///     frag_size: 8,       // 8-byte fragments
/// };
/// ```
#[repr(C)]
#[derive(Default, Debug, Clone, Copy)]
pub struct Config {
    /// Split position for HTTP/TLS request fragmentation
    /// - `-1` or `0` = disabled
    /// - positive value = byte position to split at
    pub split_pos: i32,
    /// Out-of-band data insertion position
    /// - `-1` or `0` = disabled  
    /// - positive value = byte position for OOB marker
    pub oob_pos: i32,
    /// Fake packet offset for timing attacks
    /// - `0` = disabled
    /// - positive/negative = offset value
    pub fake_offset: i32,
    /// TLS record split position
    /// - `-1` or `0` = disabled
    /// - positive value = byte position to split TLS record
    pub tlsrec_pos: i32,
    /// Enable automatic RST packet detection and handling
    pub auto_rst: bool,
    /// Enable automatic HTTP redirect detection (301/302)
    pub auto_redirect: bool,
    /// Enable automatic SSL/TLS error detection
    pub auto_ssl: bool,
    /// Enable IP fragmentation for QUIC/UDP (0 = disabled, 1 = enabled)
    pub ip_fragment: u8,
    /// Fragment size for IP fragmentation (0 = default 8 bytes)
    pub frag_size: u16,
}

/// Statistics counters from BPF
#[repr(C)]
#[derive(Debug, Clone, Copy, Default)]
pub struct Stats {
    pub packets_total: u64,
    pub packets_tcp: u64,
    pub packets_udp: u64,
    pub packets_ipv6: u64,
    pub packets_http: u64,
    pub packets_tls: u64,
    pub packets_quic: u64,
    pub packets_modified: u64,
    pub events_sent: u64,
    pub errors: u64,
}

/// Connection key - supports both IPv4 and IPv6
#[repr(C)]
#[derive(Default, Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ConnKey {
    /// IPv4: only [0] is used, rest are 0
    /// IPv6: all 4 u32 values (16 bytes total)
    pub src_ip: [u32; 4],
    pub dst_ip: [u32; 4],
    pub src_port: u16,
    pub dst_port: u16,
    /// 0 = IPv4, 1 = IPv6
    pub is_ipv6: u8,
    /// IPPROTO_TCP (6) or IPPROTO_UDP (17)
    pub proto: u8,
}

/// Event types sent from BPF to userspace via ring buffer
///
/// These events notify the userspace daemon of significant
/// network events that may require action or logging.
pub mod event_types {
    /// Fake packet injection was triggered
    pub const FAKE_TRIGGERED: u32 = 1;
    /// RST packet was detected (connection reset)
    pub const RST_DETECTED: u32 = 2;
    /// HTTP redirect (301/302) was detected
    pub const REDIRECT_DETECTED: u32 = 3;
    /// SSL/TLS fatal alert was detected
    pub const SSL_ERROR_DETECTED: u32 = 4;
    /// Packet disorder was triggered
    pub const DISORDER_TRIGGERED: u32 = 5;
}

/// Connection processing stages
///
/// Tracks the current bypass technique stage for each connection.
pub mod stages {
    /// Initial state - no processing yet
    pub const INIT: u8 = 0;
    /// Request split has been applied
    pub const SPLIT: u8 = 1;
    /// Out-of-band data has been inserted
    pub const OOB: u8 = 2;
    /// Fake packet has been sent
    pub const FAKE_SENT: u8 = 3;
    /// TLS record split has been applied
    pub const TLSREC: u8 = 4;
    /// Packet disorder has been triggered
    pub const DISORDER: u8 = 5;
}

/// Event from BPF ring buffer - supports both IPv4 and IPv6
///
/// Events are generated by the BPF program and sent to userspace
/// via a ring buffer map. They notify about detected conditions
/// such as blocked connections, redirects, or SSL errors.
///
/// # Example
/// ```
/// use goodbyedpi_proto::Event;
///
/// let event = Event {
///     event_type: 1,  // FAKE_TRIGGERED
///     src_ip: [192, 168, 1, 1].into(),
///     dst_ip: [10, 0, 0, 1].into(),
///     src_port: 54321,
///     dst_port: 443,
///     seq: 12345,
///     ack: 67890,
///     flags: 0x18,  // PSH|ACK
///     payload_len: 100,
///     is_ipv6: 0,
///     reserved: 0,
/// };
/// ```
#[repr(C)]
#[derive(Default, Debug, Clone, Copy)]
pub struct Event {
    /// Event type - one of `event_types::*`
    /// 
    /// Common values:
    /// - `1` = FAKE_TRIGGERED
    /// - `2` = RST_DETECTED
    /// - `3` = REDIRECT_DETECTED
    /// - `4` = SSL_ERROR_DETECTED
    pub event_type: u32,
    /// Source IP address
    /// - IPv4: only `[0]` is used (in network byte order)
    /// - IPv6: all 4 u32 values (16 bytes total)
    pub src_ip: [u32; 4],
    /// Destination IP address
    /// - IPv4: only `[0]` is used (in network byte order)
    /// - IPv6: all 4 u32 values (16 bytes total)
    pub dst_ip: [u32; 4],
    /// Source port (host byte order)
    pub src_port: u16,
    /// Destination port (host byte order)
    pub dst_port: u16,
    /// TCP sequence number
    pub seq: u32,
    /// TCP acknowledgment number
    pub ack: u32,
    /// TCP flags (FIN, SYN, RST, PSH, ACK, URG)
    pub flags: u8,
    /// Payload length (clamped to 255 if larger)
    pub payload_len: u8,
    /// IP version flag: `0` = IPv4, `1` = IPv6
    pub is_ipv6: u8,
    /// Padding for alignment
    pub reserved: u8,
}

impl Event {
    /// Get source IP as Ipv4Addr (only valid if is_ipv6 == 0)
    pub fn src_ip_v4(&self) -> std::net::Ipv4Addr {
        std::net::Ipv4Addr::from(u32::from_be(self.src_ip[0]))
    }

    /// Get destination IP as Ipv4Addr (only valid if is_ipv6 == 0)
    pub fn dst_ip_v4(&self) -> std::net::Ipv4Addr {
        std::net::Ipv4Addr::from(u32::from_be(self.dst_ip[0]))
    }

    /// Get source IP as Ipv6Addr (only valid if is_ipv6 == 1)
    pub fn src_ip_v6(&self) -> std::net::Ipv6Addr {
        let bytes: [u8; 16] = [
            (self.src_ip[0] >> 24) as u8, (self.src_ip[0] >> 16) as u8, 
            (self.src_ip[0] >> 8) as u8, self.src_ip[0] as u8,
            (self.src_ip[1] >> 24) as u8, (self.src_ip[1] >> 16) as u8,
            (self.src_ip[1] >> 8) as u8, self.src_ip[1] as u8,
            (self.src_ip[2] >> 24) as u8, (self.src_ip[2] >> 16) as u8,
            (self.src_ip[2] >> 8) as u8, self.src_ip[2] as u8,
            (self.src_ip[3] >> 24) as u8, (self.src_ip[3] >> 16) as u8,
            (self.src_ip[3] >> 8) as u8, self.src_ip[3] as u8,
        ];
        std::net::Ipv6Addr::from(bytes)
    }

    /// Get destination IP as Ipv6Addr (only valid if is_ipv6 == 1)
    pub fn dst_ip_v6(&self) -> std::net::Ipv6Addr {
        let bytes: [u8; 16] = [
            (self.dst_ip[0] >> 24) as u8, (self.dst_ip[0] >> 16) as u8,
            (self.dst_ip[0] >> 8) as u8, self.dst_ip[0] as u8,
            (self.dst_ip[1] >> 24) as u8, (self.dst_ip[1] >> 16) as u8,
            (self.dst_ip[1] >> 8) as u8, self.dst_ip[1] as u8,
            (self.dst_ip[2] >> 24) as u8, (self.dst_ip[2] >> 16) as u8,
            (self.dst_ip[2] >> 8) as u8, self.dst_ip[2] as u8,
            (self.dst_ip[3] >> 24) as u8, (self.dst_ip[3] >> 16) as u8,
            (self.dst_ip[3] >> 8) as u8, self.dst_ip[3] as u8,
        ];
        std::net::Ipv6Addr::from(bytes)
    }

    /// Format IP addresses for display
    pub fn format_ips(&self) -> (String, String) {
        if self.is_ipv6 != 0 {
            (format!("[{}]", self.src_ip_v6()), format!("[{}]", self.dst_ip_v6()))
        } else {
            (self.src_ip_v4().to_string(), self.dst_ip_v4().to_string())
        }
    }
}

/// Connection state stored in BPF map
///
/// Tracks the processing state for each active connection.
/// Used to coordinate multi-stage bypass techniques.
#[repr(C)]
#[derive(Default, Debug, Clone, Copy)]
pub struct ConnState {
    /// Current processing stage - one of `stages::*`
    /// 
    /// Stages:
    /// - `0` = INIT
    /// - `1` = SPLIT
    /// - `2` = OOB
    /// - `3` = FAKE_SENT
    /// - `4` = TLSREC
    pub stage: u8,
    /// Last seen TCP sequence number
    pub last_seq: u32,
    /// Last seen TCP acknowledgment number
    pub last_ack: u32,
    /// Connection flags (reserved for future use)
    pub flags: u8,
    /// Timestamp of last activity (nanoseconds since boot)
    pub timestamp: u64,
}

// Legacy constants - prefer using `stages::*` module

/// Initial state - no processing yet
pub const STAGE_INIT: u8 = 0;
/// Request split has been applied
pub const STAGE_SPLIT: u8 = 1;
/// Out-of-band data has been inserted
pub const STAGE_OOB: u8 = 2;
/// Fake packet has been sent
pub const STAGE_FAKE_SENT: u8 = 3;
/// TLS record split has been applied
pub const STAGE_TLSREC: u8 = 4;
/// Packet disorder has been triggered
pub const STAGE_DISORDER: u8 = 5;

/// Flag: Enable RST detection
pub const FLAG_AUTO_RST: u8 = 0x01;
/// Flag: Enable redirect detection  
pub const FLAG_AUTO_REDIRECT: u8 = 0x02;
/// Flag: Enable SSL error detection
pub const FLAG_AUTO_SSL: u8 = 0x04;
/// Flag: OOB (URG) was applied
pub const FLAG_OOB_APPLIED: u8 = 0x08;

/// Protocol number for TCP
pub const IPPROTO_TCP: u8 = 6;
/// Protocol number for UDP
pub const IPPROTO_UDP: u8 = 17;
